# Generated by Django 6.0.2 on 2026-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='fields',
            name='has_cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_showers',
            field=models.BooleanField(default=False),
        ),
    ]
