# Generated by Django 6.0.2 on 2026-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_location_fields_address_fields_has_cafe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
