# Generated by Django 6.0.3 on 2026-03-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='bookings',
            name='add_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_locker_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
