# Generated by Django 6.0.3 on 2026-03-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_fields_options_bookings_add_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
